"""empty message

Revision ID: 1fb03a6b6c9e
Revises: 59b1a976722e
Create Date: 2021-05-11 23:10:56.672045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1fb03a6b6c9e'
down_revision = '59b1a976722e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'attempt',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('scores', 'attempt',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
