"""Modified the user table to add more columns

Revision ID: 44055b1e4b4d
Revises: 
Create Date: 2021-05-11 18:20:56.427726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44055b1e4b4d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
